title:            Phạm Xuân Tiếp
description:      Tiếp là ai, who is Tiep?
url:              https://tiepme.netlify.com
permalink:        pretty
timezone:         America/New_York
sass:
  sass_dir: assets
  style: :compressed
collections:
  - notes
