title:            Phạm Xuân Tiếp
description:      Tiếp là ai, who is Tiep?
url:              https://www.tiep.me
permalink:        pretty
timezone:         Asia/Ho_Chi_Minh
sass:
  sass_dir: assets
  style: :compressed
collections:
  - notes

plugins: [jekyll-paginate]
paginate: 6
paginate_path: /page:num/